stages:
  train:
    cmd: '" -d" src/train.py " -d" src/prepare.py--outs-persist model/model.joblib
      -M metrics/accuracy.json python3 -m src.train'
    deps:
    - data/prepared/train.csv
  prepared:
    cmd: '" -d" src/prepare.py " -d" data/raw/train/ python3 -m src.prepare'
    outs:
    - data/prepared/test.csv:
        cache: false
